spring:
  application:
    name: backlog-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  cloud:
    config:
      uri: http://localhost:9000
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9001

