spring:
  application:
    name: backlog-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  cloud:
    config:
      uri: http://localhost:9000
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
  boot:
    admin:
      client:
        url: http://localhost:/9015
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9005/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"